{
 "title": "Dashboard práctica Roberto",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_status_phase{namespace=~\"fast-api\",phase=\"Running\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Número de accesos al servidor en la última hora",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(server_requests_total{namespace=\"fast-api\"}) - sum(min_over_time(server_requests_total{namespace=\"fast-api\"} [1h]))"
    }
   ]
  },
  {
   "title": "Número de llamadas a '/' en la última hora",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(main_requests_total{namespace=\"fast-api\"}) - sum(min_over_time(main_requests_total{namespace=\"fast-api\"} [1h]))"
    }
   ]
  },
  {
   "title": "Número de accesos a '/bye' en la última hora",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(bye_requests_total{namespace=\"fast-api\"}) - sum(min_over_time(bye_requests_total{namespace=\"fast-api\"} [1h]))"
    }
   ]
  },
  {
   "title": "Número de reinicios del pod fast-api-webapp",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{container=\"fast-api-webapp\"}"
    }
   ]
  },
  {
   "title": "Número de accesos a '/health' en la última hora",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(healthcheck_requests_total{namespace=\"fast-api\"}) - sum(min_over_time(healthcheck_requests_total{namespace=\"fast-api\"} [1h]))"
    }
   ]
  },
  {
   "title": "Número de llamadas a '/riseload' en la última hora",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(riseload_requests_total{namespace=\"fast-api\"}) - sum(min_over_time(riseload_requests_total{namespace=\"fast-api\"} [1h]))"
    }
   ]
  },
  {
   "title": "POD CPU: Consumo Vs Limite",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{pod=~\"fast-api.*\", namespace=\"fast-api\"}[1m]))",
     "legendFormat": "Uso"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"cpu\",namespace=\"fast-api\",pod=~\"fast-api-webapp.*\"}",
     "legendFormat": "CPU máxima "
    },
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"fast-api\", resource=\"cpu\",pod=~\"fast-api-webapp.*\"}",
     "legendFormat": "CPU reservada"
    }
   ]
  },
  {
   "title": "% de CPU usado",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "100 * max by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"fast-api\",pod=~\"fast-api-webapp-.*\"}[1m])) / max by(pod) (kube_pod_container_resource_limits{namespace=\"fast-api\",resource=\"cpu\"})",
     "legendFormat": "Porcentaje de CPU disponible usado"
    }
   ]
  },
  {
   "title": "Uso de RAM vs Ram reservada",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{namespace=\"fast-api\"}) by (pod)",
     "legendFormat": "Memoria usada"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"fast-api\", resource=\"memory\", pod=\"$pod\"}) by (pod)",
     "legendFormat": "Memoria reservada"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"fast-api\", resource=\"memory\", pod=\"$pod\"}) by (pod)",
     "legendFormat": "Memoria máxima"
    }
   ]
  },
  {
   "title": "Reinicios de fast-api-webapp",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "avg(kube_pod_container_status_restarts_total{namespace=\"fast-api\"}) by (pod)",
     "legendFormat": "Reinicios del pod"
    }
   ]
  }
 ]
}